# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  name: "VeracodePackage"
  env:
    VERACODE_API_KEY_ID: $(VERACODE_ID)
    VERACODE_API_KEY_SECRET: $(VERACODE_SECRET)
  inputs:
    script: |
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      ./veracode package -das . --output verascan --trust

      # Check if the verascan directory exists
      if [ ! -d "verascan" ]; then
        echo "Error: verascan directory not found."
        exit 1
      fi


- task: CmdLine@2
  name: "VeracodePipelineScan"
  env:
    VERACODE_API_KEY_ID: $(VERACODE_ID)
    VERACODE_API_KEY_SECRET: $(VERACODE_SECRET)
  inputs:
    script: |
      for file in verascan/*; do
                  	if [ -f "$file" ]; then
                  		echo "Scanning $file ..."
                  		./veracode static scan "$file"
                  	fi
                  done