# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: VeracodePipelineScan@0
  inputs:
    VeracodeAPIID: '$(vid)'
    VeracodeAPIsecret: '$(vkey)'
    fileToScan: '$(System.DefaultWorkingDirectory)/verademo.war'

- task: CmdLine@2
  inputs:
    script: |
      git clone https://github.com/tjarrettveracode/veracode-pipeline-mitigation
      pip install -r ./veracode-pipeline-mitigation/requirements.txt
      python ./veracode-pipeline-mitigation/vcpipemit.py -an "Verademo ADO" -rf pipeline-baseline-file.json
